### ISSUE TITLE
building through github actions doesn't work 

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#146]
in #122, @WIStudent introduced a build step to help us get rid of manually vendoring DOMPurify (yay), but the github actions workflow to add commits is [disallowed by the Mozilla org](https://github.com/mozilla/sanitizer-polyfill/actions/workflows/build-demo.yml).

This issue is to investigate the exact restrictions and then explore other possibilities.

**Comment by mozfreddyb** [comment]
> endbug/add-and-commit@v9 is not allowed to be used in mozilla/sanitizer-polyfill. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: !/mozilla/**, !mozilla/**, ./**, 10up/wpcs-action@*, aws-actions/*, codecov/codecov-action@v2, docker/*, pypa/gh-action-pypi-publish@v1.4.2, slackapi/slack-github-action@*, google-github-actions/*, erlef/setup-beam@v1.

**Comment by mozfreddyb** [comment]
Maybe https://github.com/marketplace/actions/branch-deploy would be able to replace add-and-commit? Not sure.

**Comment by WIStudent** [comment]
I just saw that Github added a new (beta) feature that allows to publish the github pages files from a workflow instead of adding them to the repository. https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

I haven't yet tried it myself but the workflow should then look something like this:
```yml
name: Build demo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run prettier && npm run lint
      - run: npm run build

      - name: Create temporary gh-pages-dist dir
        run: |-
          mkdir gh-pages-dist
          cp -R demo gh-pages-dist/demo/
          cp -R dist gh-pages-dist/dist/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: gh-pages-dist
  
  Deploy:
    needs: Build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

```

The `actions/upload-pages-artifact` action takes the content of the gh-pages-dist directory, zips it and uploads it as an artifact named `github-pages`. The `Deploy` job then uses the `actions/deploy-pages` action to deploy the content of the `github-pages` artifact.
